# Generated by Django 5.2.6 on 2025-09-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2048)),
                ('subtitle', models.CharField(max_length=2048)),
                ('author', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
